config:
  profile: i'm dev
  said:
    first: rabbit
    second: mq 연결되랏!!!1111222222222222222

spring:
    rabbitmq:
      host: 10.248.86.172
      port: 5672
      username: openbaton
      password: openbaton